language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
install:
  - pip install pipenv codeclimate-test-reporter
  - pipenv install --dev
script:
  - py.test
